### ISSUE TITLE
Missing some features from old cortex-debug mem viewer

### ISSUE THREAD

**Issue by Norm369** [mcu-debug/memview#5]
1. Can't copy a large array from the display to the clipboard (in cortex-debug 1.6.4 you could Ctrl-A to select all, Ctrl-C to copy).
2. Can't specify the number of elements to display (this wouldn't be necessary if it were possible to copy a specified number of elements to the clipboard)

**Comment by haneefdm** [comment]
You can cooy from the memory view now. Many versions of copy exist. Based on selection, copy entire window to clipboard or a file.

What is different however is the amount of data. Because this is a virtual window, we don't have things like select all (note that we only have few lines in memory at any given time). We may create a fixed sized memory window later. We are not sure we want to do the fixed sized window in the first place. So, I am closing this issue.

You can however scroll down and select as much as you want and it can all be copied. Even selection is virtual
